# Generated by Django 6.0.5 on 2026-05-10 23:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias de Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('faixa_idade', models.CharField(blank=True, choices=[('18-25', '18-25 anos'), ('25-35', '25-35 anos'), ('35-50', '35-50 anos'), ('50+', '50+ anos')], max_length=20)),
                ('faixa_renda', models.CharField(blank=True, choices=[('0-1000', 'Até R$ 1.000'), ('1000-3000', 'R$ 1.000 - R$ 3.000'), ('3000-5000', 'R$ 3.000 - R$ 5.000'), ('5000+', 'Acima de R$ 5.000')], max_length=20)),
                ('biografia', models.TextField(blank=True, max_length=500)),
                ('foto_perfil', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categorias_doacao', models.ManyToManyField(blank=True, to='doacoes.categoriaitem')),
            ],
            options={
                'verbose_name_plural': 'Doadores',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interesse', 'Interessado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='interesse', max_length=20)),
                ('mensagem_inicial', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Interesses',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unidade', models.CharField(default='unidade', max_length=50)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('interessado', 'Com Interessado'), ('doado', 'Doado'), ('cancelado', 'Cancelado')], default='disponivel', max_length=20)),
                ('pode_retirar_diretamente', models.BooleanField(default=True)),
                ('imagem', models.CharField(blank=True, max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doacoes.categoriaitem')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_doacao', to='doacoes.doador')),
            ],
            options={
                'verbose_name_plural': 'Itens de Doação',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mensagens',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PontoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ong', 'ONG'), ('igreja', 'Igreja'), ('escola', 'Escola'), ('reciclagem', 'Reciclagem'), ('outro', 'Outro')], max_length=50)),
                ('endereco', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horarios', models.TextField(blank=True)),
                ('capacidade_armazenamento', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tipos_item_aceitos', models.ManyToManyField(blank=True, to='doacoes.categoriaitem')),
            ],
            options={
                'verbose_name_plural': 'Pontos de Coleta',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pessoa', 'Pessoa Física'), ('ong', 'ONG'), ('igreja', 'Igreja'), ('escola', 'Escola'), ('reciclagem', 'Ponto de Reciclagem')], max_length=50)),
                ('cnpj', models.CharField(blank=True, max_length=18, unique=True)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('telefone_contato', models.CharField(blank=True, max_length=20)),
                ('publico_atendido', models.TextField(blank=True)),
                ('disponibilidade_retirada', models.BooleanField(default=False)),
                ('horarios_disponibilidade', models.CharField(blank=True, max_length=255)),
                ('sobre', models.TextField(blank=True, max_length=1000)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tipos_item_aceitos', models.ManyToManyField(blank=True, to='doacoes.categoriaitem')),
            ],
            options={
                'verbose_name_plural': 'Receptores',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('doador', 'Doador'), ('receptor', 'Receptor')], default='doador', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('aceite_termos', models.BooleanField(default=False)),
                ('data_consentimento', models.DateTimeField(blank=True, null=True)),
                ('deseja_delecao', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('referido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doacoes.usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_doaperto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuários',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.DeleteModel(
            name='Doacao',
        ),
        migrations.AddField(
            model_name='interesse',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='doacoes.itemdoacao'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='interesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doacoes.interesse'),
        ),
        migrations.AddField(
            model_name='itemdoacao',
            name='ponto_coleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doacoes.pontocoleta'),
        ),
        migrations.AddField(
            model_name='itemdoacao',
            name='receptor_confirmado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doacoes.receptor'),
        ),
        migrations.AddField(
            model_name='interesse',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.receptor'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='doacoes.usuario'),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doacoes.usuario'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='doacoes.usuario'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='doacoes.usuario'),
        ),
        migrations.AddField(
            model_name='doador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doador', to='doacoes.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='interesse',
            unique_together={('item', 'receptor')},
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['remetente', 'data_criacao'], name='doacoes_men_remeten_e9a9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['destinatario', 'lida'], name='doacoes_men_destina_4c6205_idx'),
        ),
    ]
